### ISSUE TITLE
文章和帖子页不显示正文和回复文本

### ISSUE THREAD

**Issue by Mushan3420** [Mushan3420/BigApp-PHP7#1]
文章和帖子页不显示正文和回复文本

**Comment by branchzero** [comment]
@Mushan3420  随便改了三处，先试试吧。。。不保证能行，没有测试环境，不再进一步折腾了。

**Comment by Mushan3420** [comment]
测试环境，拿我网站就可以，应用刚上线。

**Comment by Mushan3420** [comment]
@branchzero Great ! You did it ! The issue fixed !
